' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace CuentasMySQL
	
	Public Class frmCuentas
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmCuentas_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=sql3.freesqldatabase.com;user id=sql372037;password=iU5%dP6*;database=sql372037;"
			ad = New MySqlDataAdapter("select * from `Cuentas`", strConn)
			Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
			ad.Fill(Me.newDataSet.Cuentas)
			ad.DeleteCommand = builder.GetDeleteCommand()
			ad.UpdateCommand = builder.GetUpdateCommand()
			ad.InsertCommand = builder.GetInsertCommand()
			bindingNavigatorAddNewItem.Enabled = False
			bindingNavigatorCountItem.Enabled = False
			bindingNavigatorDeleteItem.Enabled = False
			bindingNavigatorMoveFirstItem.Enabled = False
			bindingNavigatorMovePreviousItem.Enabled = False
			bindingNavigatorPositionItem.Enabled = False
			bindingNavigatorMoveNextItem.Enabled = False
			bindingNavigatorMoveLastItem.Enabled = False
			toolStripButton1.Enabled = True
			dataGridView1.AutoGenerateColumns = False
            Dim strConn2 As String = "port=3306;server=sql3.freesqldatabase.com;user id=sql372037;password=iU5%dP6*;database=sql372037;"
			Dim ad2 As MySql.Data.MySqlClient.MySqlDataAdapter = Nothing
			Dim colID As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colID.DataPropertyName = "ID"
			colID.HeaderText = "ID"
            colID.Name = "colID"
            colID.ReadOnly = True
			dataGridView1.Columns.Add(colID)
			Dim colNOMBRE As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colNOMBRE.DataPropertyName = "NOMBRE"
			colNOMBRE.HeaderText = "NOMBRE"
			colNOMBRE.Name = "colNOMBRE"
			dataGridView1.Columns.Add(colNOMBRE)
			Dim colUSUARIO As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colUSUARIO.DataPropertyName = "USUARIO"
			colUSUARIO.HeaderText = "USUARIO"
			colUSUARIO.Name = "colUSUARIO"
			dataGridView1.Columns.Add(colUSUARIO)
			Dim colCONTRASENA As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colCONTRASENA.DataPropertyName = "CONTRASENA"
			colCONTRASENA.HeaderText = "CONTRASENA"
            colCONTRASENA.Name = "colCONTRASENA"
            colCONTRASENA.Width = 100
			dataGridView1.Columns.Add(colCONTRASENA)
			Dim colDESCRIPCION As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colDESCRIPCION.DataPropertyName = "DESCRIPCION"
			colDESCRIPCION.HeaderText = "DESCRIPCION"
            colDESCRIPCION.Name = "colDESCRIPCION"
            colDESCRIPCION.Width = 200
            dataGridView1.Columns.Add(colDESCRIPCION)
			Me.dataGridView1.DataSource = Me.CuentasBindingSource
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			CuentasBindingSource.EndEdit()
			ad.Update(Me.newDataSet.Cuentas)
		End Sub
		
		Private Sub frmCuentas_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
        Private Sub dataGridView1_CellValidating(sender As Object, e As DataGridViewCellValidatingEventArgs) Handles dataGridView1.CellValidating

            Dim s As String
            Dim row As DataGridViewRow = dataGridView1.Rows(e.RowIndex)
            Dim value As Object = e.FormattedValue
            e.Cancel = False
            row.ErrorText = ""
            If row.IsNewRow Then
                Return
            End If
            If e.ColumnIndex = 0 Then

                Dim v As Integer
                If (TypeOf value Is DBNull) OrElse String.IsNullOrEmpty(value.ToString()) Then
                    e.Cancel = True
                    row.ErrorText = "The field ID is required"
                    Return
                End If
                s = value.ToString()
                If Not Integer.TryParse(s, v) Then
                    e.Cancel = True
                    row.ErrorText = "The field ID must be Integer."
                    Return
                End If
            End If
            If e.ColumnIndex = 1 Then

                If (TypeOf value Is DBNull) OrElse String.IsNullOrEmpty(value.ToString()) Then
                    e.Cancel = True
                    row.ErrorText = "The field NOMBRE is required"
                    Return
                End If
            End If
            'If e.ColumnIndex = 2 Then

            '	If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
            '		e.Cancel = True
            '		row.ErrorText = "The field USUARIO is required"
            '		Return
            '	End If
            'End If
            'If e.ColumnIndex = 3 Then

            '	If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
            '		e.Cancel = True
            '		row.ErrorText = "The field CONTRASENA is required"
            '		Return
            '	End If
            'End If
            'If e.ColumnIndex = 4 Then

            '	If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
            '		e.Cancel = True
            '		row.ErrorText = "The field DESCRIPCION is required"
            '		Return
            '	End If
            'End If
        End Sub
        Private Sub dataGridView1_DataError(ByVal sender As Object, ByVal e As DataGridViewDataErrorEventArgs) Handles dataGridView1.DataError
            dataGridView1.Rows(e.RowIndex).ErrorText = e.Exception.Message
            e.Cancel = True
        End Sub
		
        Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs) Handles BindingNavigatorAddNewItem.Click
            CuentasBindingSource.AddNew()
        End Sub
		
	End Class
	
End Namespace
